# Generated by Django 2.2.5 on 2019-09-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0004_auto_20190924_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
