# Generated by Django 2.2.5 on 2019-09-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0007_auto_20190924_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='titulo',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Dra.', 'Dra.')], max_length=4, null=True),
        ),
    ]
