# Generated by Django 2.2.5 on 2019-09-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0008_auto_20190924_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name_plural': 'Pacientes'},
        ),
    ]
