# Generated by Django 2.2.5 on 2019-09-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user',), 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
