# Generated by Django 2.2.5 on 2019-09-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0003_auto_20190923_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_sem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Paciente', 'Paciente'), ('Asistente', 'Asistente'), ('Editor', 'Editor')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='titulo',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Dra.', 'Dra.')], max_length=4, null=True),
        ),
    ]
