# Generated by Django 2.2.5 on 2019-09-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0006_auto_20190924_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Paciente', 'Paciente'), ('Laboratorio', 'Laboratorio')], max_length=9, null=True),
        ),
    ]
