# Generated by Django 2.2.5 on 2019-09-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semin', '0009_auto_20190924_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='titulo',
        ),
    ]
